# Generated by Django 6.0.5 on 2026-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên sách')),
                ('author', models.CharField(max_length=100, verbose_name='Tác giả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Giá tiền')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng')),
            ],
        ),
    ]
